name: Java CI with Gradle

on:
  push:
    paths:
     - 'github-action/**'
     - 'react-action/**'
    branches: [ "develop" ]
  pull_request:
    paths:
     - 'github-action/**'
     - 'react-action/**'
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./github-action

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: develop
        repository: PARKJINHOH/github-action
        token: ${{ secrets.TOKEN_GITHUB }}

    
    - name: Cache Gradle
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Gradle wrapper & build
      working-directory: ${{ env.working-directory }}
      run: |
        chmod +x ./gradlew
        ./gradlew clean bootJar
        ls ./build/libs
        
    - name: Upload to Oracle Cloud
      uses: actions/upload-artifact@v3
      with:
        name: jar-artifact
        path: github-action/build/libs #Full Path

  
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:        
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: jar-artifact
        
    - name: pwd
      run: ls -al .

    - name: copy file via ssh password
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SSH_IP }}
        username: ubuntu
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        key: ${{ secrets.SSH_RSA }}
        source: "*.jar"
        target: ${{ secrets.DIST_PATH }}
