name: Java CI with Gradle

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./github-action

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: develop
        repository: PARKJINHOH/github-action
        token: ${{ secrets.TOKEN_GITHUB }}
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Gradle wrapper & build
      working-directory: ${{ env.working-directory }}
      run: |
        chmod +x ./gradlew
        ./gradlew build

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_IP }}
        port: 22
        username: pinner
        password: ${{ secrets.SSH_PASSWORD }}
        key: ${{ secrets.SSH_RSA }}
        script: |
          echo "Backend 테스트 출력"
