name: Java CI with Gradle

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    # env:
    #   working-directory: ./github-action

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: develop
        repository: PARKJINHOH/github-action
        token: ${{ secrets.TOKEN_GITHUB }}
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
      
    - name: Build with Gradle
      uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
      with:
        arguments: build
        build-root-directory: ./
        
    - uses: actions/upload-artifact@v3
      with:
        name: Package
        path: build/libs

